### ISSUE TITLE
在窗口上加载一个 ico 文件

### ISSUE THREAD

**Issue by liukuo362573** [Mzying2001/sw#1]
感谢大佬提供的框架，请问怎么在窗口上加载一个 ico 文件，类似 C# 的 picturebox 控件？

**Comment by Mzying2001** [comment]
目前暂时还没有 `PictureBox` 控件（最近比较忙没时间更新，等后面有时间了会加上），要显示 ico 文件的话可以利用 `STATIC` 控件（设置 `SS_ICON` 样式），写个类继承自 `Control` 即可，下面是简单的示例：

```c++
class IconBox : public sw::Control
{
public:
    IconBox()
    {
        this->InitControl(L"STATIC", L"", WS_VISIBLE | WS_CHILD | WS_CLIPSIBLINGS | SS_ICON, 0);
    }

    void SetIcon(HICON hIcon)
    {
        this->SendMessageW(STM_SETICON, reinterpret_cast<WPARAM>(hIcon), 0);
    }
};
```

下面是简单的使用示例：

```c++
class MyWindow : public sw::Window
{
    IconBox icon; // 图标控件
    HICON hIcon;  // 图标

public:
    MyWindow()
    {
        this->SetLayout<sw::DockLayout>();

        // 加载图标文件
        hIcon = (HICON)::LoadImageW(NULL, L"test.ico", IMAGE_ICON, 0, 0, LR_LOADFROMFILE | LR_DEFAULTSIZE);

        // 设置图标并添加到界面
        icon.SetIcon(hIcon);
        icon.Rect = sw::Rect(0, 0, 20, 20);
        this->AddChild(icon);
    }

    ~MyWindow()
    {
        ::DestroyIcon(hIcon); // 释放资源
    }
};

int main()
{
    auto mainWindow = std::make_unique<MyWindow>();
    mainWindow->Show();
    return sw::App::MsgLoop();
}
```

资料：
https://learn.microsoft.com/en-us/windows/win32/controls/static-control-styles
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadimagew

**Comment by liukuo362573** [comment]
感谢大佬及时的回复，解决了我的问题。
`		icon.RegisterRoutedEvent(sw::UIElement_MouseMove, [this](UIElement& sender, sw::RoutedEventArgs& e) {
			auto& mme = static_cast<sw::MouseMoveEventArgs&>(e);
			 

			});`
icon 注册了鼠标移动事件，不执行。

**Comment by Mzying2001** [comment]
STATIC 默认是不会触发事件的，要的话得添加 SS_NOTIFY 样式，在调用 InitControl 那里加上应该就行了。
&nbsp;


Mzying2001
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月27日(星期三) 中午11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mzying2001/sw] 在窗口上加载一个 ico 文件 (Issue #1)





 
感谢大佬及时的回复，解决了我的问题。
 `		icon.RegisterRoutedEvent(sw::UIElement_MouseMove, [this](UIElement&amp; sender, sw::RoutedEventArgs&amp; e) {
 auto&amp; mme = static_castsw::MouseMoveEventArgs&amp;(e);
 		});`  
icon 注册了鼠标移动事件，不执行。

**Comment by liukuo362573** [comment]
谢谢大佬。
